return {
  "nvim-treesitter/nvim-treesitter",
  events = "UIEnter",
  version = false, -- last release is way too old and doesn't work on Windows
  build = ":TSUpdate",
  -- event = "VeryLazy",
  -- lazy = vim.fn.argc(-1) == 0, -- load treesitter early when opening a file from the cmdline
  -- cmd = { "TSUpdateSync", "TSUpdate", "TSInstall" },
  opts = {
    highlight = { enable = true },
    indent = { enable = true },
    ensure_installed = {
      "bash",
      "c",
      "diff",
      "html",
      "javascript",
      "jsdoc",
      "json",
      "jsonc",
      "lua",
      "luadoc",
      "luap",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "typst",
      "regex",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "xml",
      "yaml",
      "go",
      "typst",
    },
  },
}
